apiVersion: v1
kind: Job
metadata:
  name: cleanup-old-logs
  tenant: acme-corp
  labels:
    env: production
    team: platform
    criticality: low
  annotations:
    owner: ops-team@acme.com
    description: "Removes log files older than 90 days"
spec:
  # Run daily at 3 AM UTC
  schedule: "0 3 * * *"
  timezone: UTC
  
  # Cleanup command
  command: /usr/bin/find
  args:
    - /var/log/applications
    - -type
    - f
    - -mtime
    - +90
    - -delete
  
  # Check-in
  checkin:
    enabled: true
    secret: ${CLEANUP_CHECKIN_SECRET}
    timeout: 600  # 10 minutes max
  
  enabled: true
