agent:
  name: "my-agent"
  hostname: "localhost"
  platform: "darwin"
  version: "0.1.0"
  token_path: "~/.crontopus/agent-token"

backend:
  api_url: "http://localhost:8000"
  # Get this token from: cat ~/.crontopus/token | python3 -c "import json,sys; print(json.load(sys.stdin)['access_token'])"
  enrollment_token: "YOUR_USER_TOKEN_HERE"
