"""add_tenants_and_users_tables

Revision ID: 1e1a2b0d1051
Revises: ca0898ff5097
Create Date: 2025-10-28 08:57:38.156871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1a2b0d1051'
down_revision: Union[str, None] = 'ca0898ff5097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
