"""add_enrollment_tokens_table

Revision ID: e3f87db142ee
Revises: 15f02fc423e9
Create Date: 2025-11-09 15:23:49.608734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f87db142ee'
down_revision: Union[str, None] = '15f02fc423e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'REVOKED', name='agentstatus'), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('git_repo_url', sa.String(length=512), nullable=True),
    sa.Column('git_branch', sa.String(length=255), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_id'), 'agent', ['id'], unique=False)
    op.create_index(op.f('ix_agent_name'), 'agent', ['name'], unique=False)
    op.create_index(op.f('ix_agent_status'), 'agent', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tenant_id'), 'agent', ['tenant_id'], unique=False)
    op.create_table('enrollment_token',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_token_id'), 'enrollment_token', ['id'], unique=False)
    op.create_index(op.f('ix_enrollment_token_tenant_id'), 'enrollment_token', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_enrollment_token_token_hash'), 'enrollment_token', ['token_hash'], unique=True)
    op.create_table('job_instance',
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'RUNNING', 'PAUSED', 'ERROR', name='jobinstancestatus'), nullable=False),
    sa.Column('source', sa.Enum('GIT', 'DISCOVERED', name='jobinstancesource'), nullable=False),
    sa.Column('original_command', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_instance_endpoint_id'), 'job_instance', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_job_instance_id'), 'job_instance', ['id'], unique=False)
    op.create_index(op.f('ix_job_instance_job_name'), 'job_instance', ['job_name'], unique=False)
    op.create_index(op.f('ix_job_instance_namespace'), 'job_instance', ['namespace'], unique=False)
    op.create_index(op.f('ix_job_instance_source'), 'job_instance', ['source'], unique=False)
    op.create_index(op.f('ix_job_instance_status'), 'job_instance', ['status'], unique=False)
    op.create_index(op.f('ix_job_instance_tenant_id'), 'job_instance', ['tenant_id'], unique=False)
    op.drop_index('ix_job_instances_endpoint_id', table_name='job_instances')
    op.drop_index('ix_job_instances_job_name', table_name='job_instances')
    op.drop_index('ix_job_instances_namespace', table_name='job_instances')
    op.drop_index('ix_job_instances_source', table_name='job_instances')
    op.drop_index('ix_job_instances_status', table_name='job_instances')
    op.drop_index('ix_job_instances_tenant_id', table_name='job_instances')
    op.drop_table('job_instances')
    op.drop_index('ix_agent_id', table_name='endpoint')
    op.drop_index('ix_agent_name', table_name='endpoint')
    op.drop_index('ix_agent_status', table_name='endpoint')
    op.drop_index('ix_agent_tenant_id', table_name='endpoint')
    op.create_index(op.f('ix_endpoint_id'), 'endpoint', ['id'], unique=False)
    op.create_index(op.f('ix_endpoint_name'), 'endpoint', ['name'], unique=False)
    op.create_index(op.f('ix_endpoint_status'), 'endpoint', ['status'], unique=False)
    op.create_index(op.f('ix_endpoint_tenant_id'), 'endpoint', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoint_tenant_id'), table_name='endpoint')
    op.drop_index(op.f('ix_endpoint_status'), table_name='endpoint')
    op.drop_index(op.f('ix_endpoint_name'), table_name='endpoint')
    op.drop_index(op.f('ix_endpoint_id'), table_name='endpoint')
    op.create_index('ix_agent_tenant_id', 'endpoint', ['tenant_id'], unique=False)
    op.create_index('ix_agent_status', 'endpoint', ['status'], unique=False)
    op.create_index('ix_agent_name', 'endpoint', ['name'], unique=False)
    op.create_index('ix_agent_id', 'endpoint', ['id'], unique=False)
    op.create_table('job_instances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('job_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('namespace', sa.VARCHAR(length=255), nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('original_command', sa.TEXT(), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_instances_tenant_id', 'job_instances', ['tenant_id'], unique=False)
    op.create_index('ix_job_instances_status', 'job_instances', ['status'], unique=False)
    op.create_index('ix_job_instances_source', 'job_instances', ['source'], unique=False)
    op.create_index('ix_job_instances_namespace', 'job_instances', ['namespace'], unique=False)
    op.create_index('ix_job_instances_job_name', 'job_instances', ['job_name'], unique=False)
    op.create_index('ix_job_instances_endpoint_id', 'job_instances', ['endpoint_id'], unique=False)
    op.drop_index(op.f('ix_job_instance_tenant_id'), table_name='job_instance')
    op.drop_index(op.f('ix_job_instance_status'), table_name='job_instance')
    op.drop_index(op.f('ix_job_instance_source'), table_name='job_instance')
    op.drop_index(op.f('ix_job_instance_namespace'), table_name='job_instance')
    op.drop_index(op.f('ix_job_instance_job_name'), table_name='job_instance')
    op.drop_index(op.f('ix_job_instance_id'), table_name='job_instance')
    op.drop_index(op.f('ix_job_instance_endpoint_id'), table_name='job_instance')
    op.drop_table('job_instance')
    op.drop_index(op.f('ix_enrollment_token_token_hash'), table_name='enrollment_token')
    op.drop_index(op.f('ix_enrollment_token_tenant_id'), table_name='enrollment_token')
    op.drop_index(op.f('ix_enrollment_token_id'), table_name='enrollment_token')
    op.drop_table('enrollment_token')
    op.drop_index(op.f('ix_agent_tenant_id'), table_name='agent')
    op.drop_index(op.f('ix_agent_status'), table_name='agent')
    op.drop_index(op.f('ix_agent_name'), table_name='agent')
    op.drop_index(op.f('ix_agent_id'), table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###
